### ISSUE TITLE
error in run

### ISSUE THREAD

**Issue by zohreh3906** [lukecq1231/kim#10]
I have python 2 and theano 0.9.0
I run the following code:
!python2 /content/drive/'My Drive'/kim/scripts/kim/train.py
But I encountered the following error:
Traceback (most recent call last):
  File "/content/drive/My Drive/kim/scripts/kim/train.py", line 4, in <module>
    from main import train
  File "/content/drive/My Drive/kim/scripts/kim/main.py", line 4, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 80, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/__init__.py", line 9, in <module>
    from theano.tensor.subtensor import *
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 27, in <module>
    from cutils_ext.cutils_ext import inplace_increment
ImportError: cannot import name inplace_increment

But when I install theano 1.0.0 , I encounter the following error

Loading knowledge base ...
2018-11-27 11:25:53,537: main: DEBUG: {'attention_lambda': 0,
 'batch_size': 32,
 'clip_c': 10.0,
 'datasets': ['../../data/sequence_and_features/premise_snli_1.0_train_token.txt',
              '../../data/sequence_and_features/hypothesis_snli_1.0_train_token.txt',
              '../../data/sequence_and_features/premise_snli_1.0_train_lemma.txt',
              '../../data/sequence_and_features/hypothesis_snli_1.0_train_lemma.txt',
              '../../data/sequence_and_features/label_snli_1.0_train.txt'],
 'decay_c': 0.0,
 'decoder': 'lstm',
 'dictionary': ['../../data/sequence_and_features/vocab_cased.pkl',
                '../../data/sequence_and_features/vocab_cased_lemma.pkl'],
 'dim': 300,
 'dim_kb': 5,
 'dim_word': 300,
 'dispFreq': 100,
 'embedding': '../../data/glove/glove.840B.300d.txt',
 'encoder': 'lstm',
 'finish_after': 10000000,
 'kb_composition': False,
 'kb_dicts': ['../../data/sequence_and_features/pair_features.pkl'],
 'kb_inference': True,
 'lrate': 0.0004,
 'max_epochs': 5000,
 'maxlen': 100,
 'n_words': 110497,
 'n_words_lemma': 100360,
 'optimizer': 'adam',
 'patience': 7,
 'reload_': False,
 'saveFreq': 17168,
 'saveto': '../../models/kim.npz',
 'test_datasets': ['../../data/sequence_and_features/premise_snli_1.0_test_token.txt',
                   '../../data/sequence_and_features/hypothesis_snli_1.0_test_token.txt',
                   '../../data/sequence_and_features/premise_snli_1.0_test_lemma.txt',
                   '../../data/sequence_and_features/hypothesis_snli_1.0_test_lemma.txt',
                   '../../data/sequence_and_features/label_snli_1.0_test.txt'],
 'use_dropout': True,
 'validFreq': 17168,
 'valid_batch_size': 32,
 'valid_datasets': ['../../data/sequence_and_features/premise_snli_1.0_dev_token.txt',
                    '../../data/sequence_and_features/hypothesis_snli_1.0_dev_token.txt',
                    '../../data/sequence_and_features/premise_snli_1.0_dev_lemma.txt',
                    '../../data/sequence_and_features/hypothesis_snli_1.0_dev_lemma.txt',
                    '../../data/sequence_and_features/label_snli_1.0_dev.txt'],
 'verbose': False}
Loading data
Building model
Wemb (110497, 300)
encoder_W (300, 1200)
encoder_U (300, 1200)
encoder_b (1200,)
encoder_r_W (300, 1200)
encoder_r_U (300, 1200)
encoder_r_b (1200,)
decoder_W (305, 1200)
decoder_U (300, 1200)
decoder_b (1200,)
decoder_r_W (305, 1200)
decoder_r_U (300, 1200)
decoder_r_b (1200,)
projection_W (2405, 300)
projection_b (300,)
ff_layer_1_W (2400, 300)
ff_layer_1_b (300,)
ff_layer_output_W (300, 3)
ff_layer_output_b (3,)
Traceback (most recent call last):
  File "/content/drive/My Drive/kim/scripts/kim/train.py", line 50, in <module>
    attention_lambda = 0,
  File "/content/drive/My Drive/kim/scripts/kim/main.py", line 866, in train
    build_model(tparams, model_options)
  File "/content/drive/My Drive/kim/scripts/kim/main.py", line 552, in build_model
    mask=x1_mask)
  File "/content/drive/My Drive/kim/scripts/kim/main.py", line 356, in lstm_layer
    n_steps=nsteps, profile=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 1076, in scan
    scan_outs = local_op(*scan_inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 546, in make_node
    inner_sitsot_out.type.dtype))
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 2) has dtype float32, while the result of the inner function (`fn`) has dtype float64. This can happen if the inner function of scan results in an upcast or downcast.
Please help me.

**Comment by lukecq1231** [comment]
Sorry I can't give you more suggestions, because I didn't try the experiments on Colab. I could run the code with anaconda + python2.7 + theano 0.9 on local machine.
